import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Payout } from '../types/payout';

/**
 * Generates a professional "Bespoke Financial Statement" PDF for a payout.
 * Designed for elite banking aesthetics with high legibility.
 */
export const generatePayoutPDF = (payout: Payout) => {
    const doc = new jsPDF();
    const primaryColor: [number, number, number] = [24, 97, 49]; // --primary: #186131;
    const margin = 20;

    // 1. Header Section
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.setTextColor(33, 37, 41);
    doc.text('Settlement Statement', margin, 30);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(102, 112, 133);
    doc.text(`Official Settlement Record ID: ${payout.id}`, margin, 38);
    doc.text(`Transaction Nexus: ${payout.source.orderId}`, margin, 43);

    // Status Badge
    const status = payout.status.toUpperCase();
    const statusColor: [number, number, number] = payout.status === 'paid' ? [16, 185, 129] : [24, 97, 49];
    doc.setFillColor(statusColor[0], statusColor[1], statusColor[2]);
    doc.rect(160, 24, 30, 8, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.text(status, 175, 29.5, { align: 'center' });

    // 2. Executive Summary Box
    doc.setDrawColor(230, 230, 230);
    doc.setFillColor(249, 250, 251);
    doc.rect(margin, 55, 170, 35, 'FD');

    doc.setFontSize(9);
    doc.setTextColor(102, 112, 133);
    doc.text('Beneficiary Name', margin + 10, 68);
    doc.text('Settlement Date', margin + 110, 68);
    doc.text('Total Net Amount', margin + 10, 78);
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(33, 37, 41);
    doc.text(payout.farmerName.toUpperCase(), margin + 10, 73);
    doc.text(payout.date, margin + 110, 73);
    doc.setFontSize(14);
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.text(`${payout.currency} ${payout.amount.toLocaleString(undefined, { minimumFractionDigits: 2 })}`, margin + 10, 84);

    // 3. Financial Breakdown Table
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(33, 37, 41);
    doc.text('FINANCIAL DISTRIBUTION LEDGER', margin, 105);

    autoTable(doc, {
        startY: 110,
        margin: { left: margin, right: margin },
        head: [['Entry Description', 'Allocation / Unit Value']],
        body: [
            ['Standard Contract Yield Base', `ETB ${payout.breakdown.baseAmount.toLocaleString()}`],
            ['Premium Quality Multiplier', `+ ETB ${payout.breakdown.qualityBonus.toLocaleString()}`],
            ['Association Service Levy', `- ETB ${payout.breakdown.deductions.toLocaleString()}`],
            ['PRICE PER UNIT (Q)', `ETB ${payout.breakdown.pricePerKuntal.toLocaleString()}`],
            ['TOTAL VOLUME CONTRIBUTED', `${payout.source.contributionQuantity.toLocaleString()} KUNTAL`],
        ],
        theme: 'striped',
        headStyles: { 
            fillColor: [245, 245, 245], 
            textColor: [102, 112, 133],
            fontSize: 8,
            fontStyle: 'bold'
        },
        columnStyles: {
            1: { halign: 'right', fontStyle: 'bold' }
        },
        styles: {
            fontSize: 9,
            cellPadding: 5
        }
    });

    // 4. Audit History Section
    const finalY = (doc as any).lastAutoTable.finalY || 150;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('AUDIT TRACE LOG', margin, finalY + 20);

    const auditBody = payout.auditLogs?.map(log => [
        log.timestamp,
        log.action.replace(/_/g, ' ').toUpperCase(),
        log.userName || 'SYSTEM'
    ]) || [[payout.date, 'INITIAL RECORD', 'LEDGER']];

    autoTable(doc, {
        startY: finalY + 25,
        margin: { left: margin, right: margin },
        head: [['Timestamp', 'Authorized Action', 'Operator']],
        body: auditBody,
        theme: 'plain',
        headStyles: { 
            fontSize: 7,
            textColor: [150, 150, 150],
            fontStyle: 'bold'
        },
        styles: {
            fontSize: 8,
            cellPadding: 3
        }
    });

    // 5. Footer HUD
    const pageHeight = doc.internal.pageSize.height;
    doc.setDrawColor(230, 230, 230);
    doc.line(margin, pageHeight - 30, 190, pageHeight - 30);
    
    doc.setFontSize(7);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by KuntalX Trust Engine v4.2 - SECURE TRANSACTION CONFIRMATION', margin, pageHeight - 20);
    doc.text('Valid only with official ledger sync. Non-transferable statement of account.', margin, pageHeight - 16);

    // Save PDF
    doc.save(`KuntalX_Statement_${payout.id.substring(0, 8)}.pdf`);
};
